/* Copyright 2001-2004 Roger Dingledine.
 * Copyright (c) 2004-2006, Roger Dingledine, Nick Mathewson.
 * Copyright (c) 2007-2015, The Tor Project, Inc. */
/* See LICENSE for licensing information */
#ifndef TOR_LIBTOR_H
#define TOR_LIBTOR_H

/** String describing which Tor Git repository version the source was
 * built from.  This string is generated by a bit of shell kludging in
 * src/or/include.am, and is usually right.
 */
extern const char tor_git_revision[];

#ifndef TOR_LIBTOR_GIT_REVISION_DEFINED
#define TOR_LIBTOR_GIT_REVISION_DEFINED
const char tor_git_revision[] =
#ifndef _MSC_VER
#include <tor/micro-revision.i>
#endif
  "";
#endif

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \file tor_main.c
 * \brief Stub module containing a main() function. Allows unit
 * test binary to link against main.c.
 **/
int tor_main(int argc, char **argv);

#ifdef __cplusplus
}
#endif

#endif
