#!/bin/sh -e
# Part of measurement-kit <https://measurement-kit.github.io/>.
# Measurement-kit is free software. See AUTHORS and LICENSE for more
# information on the copying conditions.

mkpm_root=`pwd`/mkpm_modules
if [ -f $mkpm_root/.installed/$1 ]; then
    rm -f $mkpm_root/.installed/$1
fi
