#!/bin/sh -e
# Part of measurement-kit <https://measurement-kit.github.io/>.
# Measurement-kit is free software. See AUTHORS and LICENSE for more
# information on the copying conditions.

if [ "$mkpm_debug" ]; then set -x; fi

scriptdir=$(cd $(dirname $0) && pwd -P) 

mkpm_root=`pwd`/mkpm_modules
mkpm_spec_repo=https://raw.githubusercontent.com/bassosimone/mkpm-install
if [ -z "$mkpm_spec_branch" ]; then
    mkpm_spec_branch=master
fi

mkpm_get_resource() {
    install -d $mkpm_root/resource/`dirname $1`
    if [ ! -f $mkpm_root/$1 ]; then
        echo "get remote resource: $1"
        curl -#o $mkpm_root/resource/$1                                        \
            $mkpm_spec_repo/$mkpm_spec_branch/mkpm_modules/$1
    else
        echo "prefer local resource: $1"
        cp $mkpm_root/$1 $mkpm_root/resource/$1
    fi
}
mkpm_apply_patch() {
    mkpm_get_resource $1
    git apply $mkpm_root/resource/$1
}
mkpm_install_resource() {
    mkpm_get_resource $1
    install $mkpm_root/resource/$1 $2
}

if [ $# -lt 1 ]; then
    echo "usage: $0 package [phase...]"
    echo "  available phases: depend, clone, configure, make, install"
    echo "  by default all phases are executed"
    exit 0
fi
if [ $# -eq 1 ]; then
    set -- $1 depend clone configure make install
fi

install -d $mkpm_root
install -d $mkpm_root/deps
install -d $mkpm_root/dist
install -d $mkpm_root/installed
install -d $mkpm_root/resource
install -d $mkpm_root/src

pkg_depend() {
    if [ -f $mkpm_root/installed/$pkg_name ]; then
        echo "$pkg_name: already installed"
        echo "run '$scriptdir/mkpm rm $pkg_name' to remove it"
        exit 0
    fi
    if [ -f $mkpm_root/deps/$pkg_name ]; then
        echo "$pkg_name: detected dependencies loop"
        exit 0
    fi
    touch $mkpm_root/deps/$pkg_name
    for dep in $pkg_deps; do
        echo "$pkg_name: dependency: '$dep'"
        $0 $dep
    done
    rm $mkpm_root/deps/$pkg_name
}

pkg_clone() {
    cd $mkpm_root/src
    rm -rf $pkg_name
    if [ ! -z "$pkg_repo" ]; then
        git clone --depth=4 --branch=$pkg_branch $pkg_repo
    else
        mkdir $mkpm_root/src/$pkg_name  # Following steps assume this
    fi
}

pkg_configure() {
    cd $mkpm_root/src/$pkg_name
    if [ -x autogen.sh ]; then
        ./autogen.sh
    elif [ -f configure.ac -o -f configure.in ]; then
        autoreconf -i
    fi
    if [ -x configure ]; then
        ./configure --prefix=$mkpm_root/dist $mkpm_configure_flags
    fi
}

pkg_make() {
    cd $mkpm_root/src/$pkg_name
    if [ -f Makefile ]; then
        make $mkpm_make_flags
    fi
}

pkg_install() {
    cd $mkpm_root/src/$pkg_name
    if [ -f Makefile ]; then
        make install $mkpm_make_flags
    fi
}

# This used to be a larger script relying on subshells and `set -e` to
# catch and handle errors, but turned out to be non-portable, hence the
# implementation has been splitted in multiple scripts.
#
# The objective of this script is to build *just one* package, eventually
# modifying the environment, possibly dying on error (set -e), and discarding
# any changes made to environment on exit.
#
# Hopefully this would be enough to plase travis.
#
#    - Written by a very frustrated Simone on 2016-01-06.

pkg=$1
shift
echo "* $pkg"

# Allow ./configure to find what we've compiled
export CPPFLAGS="$CPPFLAGS -I$mkpm_root/dist/include"
export LDFLAGS="$LDFLAGS -L$mkpm_root/dist/lib"

echo "- spec($pkg)"
mkpm_get_resource pkg/$pkg/spec.sh
. $mkpm_root/resource/pkg/$pkg/spec.sh
test -z "$pkg_branch" && pkg_branch=master

saved_pwd=`pwd`  # save directory
for phase in $@; do
    echo "- $phase($pkg)"
    pkg_${phase}
    cd $saved_pwd   # restore
done
touch $mkpm_root/installed/$pkg_name
