#!/bin/sh -e
# Part of measurement-kit <https://measurement-kit.github.io/>.
# Measurement-kit is free software. See AUTHORS and LICENSE for more
# information on the copying conditions.

if [ "$mkpm_debug" ]; then
    set -x
fi

mkpm_root=`pwd`/mkpm_modules
mkpm_spec_repo=https://raw.githubusercontent.com/bassosimone/mkpm-install
mkpm_spec_branch=master

mk_pkg_clone() {
    cd $mkpm_root/src
    rm -rf $mk_pkg_name
    git clone --depth=4 --branch=$mk_pkg_branch $mk_pkg_repo
}

mk_pkg_configure() {
    cd $mkpm_root/src/$mk_pkg_name
    if [ -x autogen.sh ]; then
        ./autogen.sh
    elif [ -f configure.ac -o -f configure.in ]; then
        autoreconf -i
    fi
    if [ -x configure ]; then
        ./configure --prefix=$mkpm_root/dist $mkpm_configure_flags
    fi
}

mk_pkg_make() {
    cd $mkpm_root/src/$mk_pkg_name
    if [ -f Makefile ]; then
        make $mkpm_make_flags
    fi
}

mk_pkg_install() {
    cd $mkpm_root/src/$mk_pkg_name
    if [ -f Makefile ]; then
        make install $mkpm_make_flags
    fi
}

mkpm_get_resource() {
    install -d $mkpm_root/`dirname $1`
    if [ ! -f $mkpm_root/$1 ]; then
        curl -O $mkpm_root/$1 $mkpm_spec_repo/$mkpm_spec_branch/mkpm_modules/$1
    fi
}
mkpm_apply_patch() {
    mkpm_get_resource $1
    git apply $mkpm_root/$1
}
mkpm_install_resource() {
    mkpm_get_resource $1
    install $mkpm_root/$1 $2
}

install -d $mkpm_root
install -d $mkpm_root/src
install -d $mkpm_root/dist
while [ $# -gt 0 ]; do (
        echo "= $1"

        echo "== source $1 spec =="
        mkpm_get_resource pkg/$1/spec.sh
        . $mkpm_root/pkg/$1/spec.sh
        test -z "$mk_pkg_branch" && mk_pkg_branch=master

        echo "== clone $1 =="
        (mk_pkg_clone)

        echo "== configure $1 =="
        (mk_pkg_configure)

        echo "== make $1 =="
        (mk_pkg_make)

        echo "== install $1 =="
        (mk_pkg_install)
    )
    shift
done
