#!/bin/sh -e
# Part of measurement-kit <https://measurement-kit.github.io/>.
# Measurement-kit is free software. See AUTHORS and LICENSE for more
# information on the copying conditions.

mkpm_root=`pwd`/mkpm_modules
mkpm_spec_repo=https://raw.githubusercontent.com/bassosimone/mkpm-install
mkpm_spec_branch=master

for name in Doxyfile.in Makefile.am configure.ac .clang-format .gitignore      \
            .travis.yml autogen.sh include.am; do
    curl -#O $mkpm_spec_repo/$mkpm_spec_branch/template/$name
done
chmod +x autogen.sh

install -d m4
curl -#o m4/mkpm.m4 $mkpm_spec_repo/$mkpm_spec_branch/template/m4/mkpm.m4

install -d script
for name in mkpm-cross-ios-plumbing mkpm-install mkpm-install-plumbing         \
            mkpm-autohelp mkpm mkpm-shell; do
    curl -#o script/$name $mkpm_spec_repo/$mkpm_spec_branch/script/$name
    chmod +x script/$name
done

# Update self. Must be last operation
curl -#o script/x $mkpm_spec_repo/$mkpm_spec_branch/script/mkpm-scaffolding
chmod +x script/x
mv script/x script/mkpm-scaffolding
