#!/bin/sh -e
# Part of measurement-kit <https://measurement-kit.github.io/>.
# Measurement-kit is free software. See AUTHORS and LICENSE for more
# information on the copying conditions.

mkpm_root=`pwd`/mkpm_modules
mkpm_spec_repo=https://raw.githubusercontent.com/bassosimone/mkpm-install
mkpm_spec_branch=master
if [ -z "$mkpm_spec_branch" ]; then
    mkpm_spec_branch=master
fi

# Download script that will update all the scaffolding
install -d $mkpm_root/script
echo "$mkpm_root/script/up:"
curl -#o $mkpm_root/script/up $mkpm_spec_repo/$mkpm_spec_branch/script/up
chmod +x $mkpm_root/script/up
exec $mkpm_root/script/up
